UPDATE tankdb.tk_project SET project_name = '非项目任务', project_code = 'Other', project_text = '非项目任务，如：公司总体会议、请假等。', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = null, project_end = null, project_to_dept = '0001', project_to_user = 1, project_status = 23, project_remark = '', project_lastupdate = '2015-05-20 23:16:49', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 1;
UPDATE tankdb.tk_project SET project_name = '石河子诚通物流中心项目咨询', project_code = '', project_text = '主要包括项目概念性规划、项目一期工可及资金申请报告', project_type = 23, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-07-01', project_end = '2014-10-01', project_to_dept = '', project_to_user = 2, project_status = 24, project_remark = '', project_lastupdate = '2015-05-20 23:18:30', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 4;
UPDATE tankdb.tk_project SET project_name = '无锡西站物流枢纽工可及资金申请报告项目', project_code = '', project_text = '<p style="text-indent:28.0pt;">
	项目主要由孙鹏、方怡沁、刘影三人完成报告主题部分的编制，杨伯制图。<span></span> 
</p>
<p style="text-indent:28.0pt;">
	其中方怡沁主要负责市场分析与需求中的现状、市场、预测三节以及建设规模分析，编制内容可以借鉴无锡空港项目，但注意年限的更新和范围主要货类的差异，注意多用入驻企业和市场调研数据，力争地气十足。<span></span> 
</p>
<p style="text-indent:28.0pt;">
	刘影主要开展园区交通组织、投资、财务预审会评价部分内容，流线部分注意处理项目独立地块特征不强的问题。<span></span> 
</p>
<p style="text-indent:28.0pt;">
	<br />
</p>
<p style="text-indent:28.0pt;">
	其余部分孙鹏负责。<span></span> 
</p>', project_type = 23, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-08-01', project_end = '2014-08-20', project_to_dept = '', project_to_user = 3, project_status = 5, project_remark = '', project_lastupdate = '2015-05-20 23:18:32', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 5;
UPDATE tankdb.tk_project SET project_name = '指令性任务-物流园区工可编制指南', project_code = '', project_text = '<p>
	部指令性课题
</p>
<p>
	主管总工：王压帝总工
</p>
<p>
	主管所长：张立彬副所长
</p>
<p>
	<br />
</p>', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-02-01', project_end = '2014-12-01', project_to_dept = '', project_to_user = 10, project_status = 24, project_remark = '', project_lastupdate = '2015-05-20 23:16:59', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 6;
UPDATE tankdb.tk_project SET project_name = '部综合运输体制调研（规划与发展机制）', project_code = '', project_text = '部长带队调研', project_type = 23, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-07-01', project_end = '2014-10-01', project_to_dept = '', project_to_user = 2, project_status = 4, project_remark = '', project_lastupdate = '2015-05-20 23:18:42', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 7;
UPDATE tankdb.tk_project SET project_name = '亚行综合运输论坛筹备', project_code = '', project_text = '', project_type = 24, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-08-08', project_end = '2014-11-01', project_to_dept = '', project_to_user = 2, project_status = 2, project_remark = '', project_lastupdate = '2015-05-20 23:18:46', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 8;
UPDATE tankdb.tk_project SET project_name = '湖北物流园区布局规划', project_code = '', project_text = '', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2013-07-01', project_end = '2014-08-31', project_to_dept = '', project_to_user = 2, project_status = 6, project_remark = '', project_lastupdate = '2015-05-20 23:16:51', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 9;
UPDATE tankdb.tk_project SET project_name = '象山现代物流园区公共服务中心工可和项目建议书', project_code = '', project_text = '', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2013-08-01', project_end = '2014-08-01', project_to_dept = '', project_to_user = 4, project_status = 8, project_remark = '', project_lastupdate = '2015-05-20 23:19:16', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 10;
UPDATE tankdb.tk_project SET project_name = '荆门公铁物流中心总体规划', project_code = '', project_text = '项目主要由何力武、孙鹏、李田野、李悦四人完成报告主题部分的编制，杨伯制图。<span></span> 
<p style="text-indent:28pt;">
	其中孙鹏主要负责需求分析以及建设规模分析，编制内容可以借鉴无锡空港项目，但注意年限的更新和范围主要货类的差异，注意多用入驻企业和市场调研数据，力争地气十足。<span></span> 
</p>
<p style="text-indent:28pt;">
	&nbsp;李田野主要开展园区交通组织、部分内容，流线部分注意处理项目独立地块特征不强的问题。<span></span> 
</p>
<p style="text-indent:28pt;">
	李悦主要负责信息化建设方案、开发运营模式和分期实施方案等部分，分析实施需要对接项目整体功能布局，开发运营模式需要结合当地现实
</p>
<p style="text-indent:28pt;">
	其余部分孙鹏负责。<span></span> 
</p>', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-03-19', project_end = '2014-10-09', project_to_dept = '', project_to_user = 4, project_status = 7, project_remark = '', project_lastupdate = '2015-05-20 23:16:53', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 11;
UPDATE tankdb.tk_project SET project_name = '部政务督查改进工作方案', project_code = '', project_text = '', project_type = 24, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-07-10', project_end = '2014-10-01', project_to_dept = '', project_to_user = 4, project_status = 24, project_remark = '', project_lastupdate = '2015-05-20 23:18:50', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 12;
UPDATE tankdb.tk_project SET project_name = '基于综合运输统计的“十三五”交通运输需求分析及预测专题调研', project_code = '', project_text = '', project_type = 24, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-07-24', project_end = '2014-12-01', project_to_dept = '', project_to_user = 4, project_status = 24, project_remark = '', project_lastupdate = '2015-05-20 23:18:48', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 13;
UPDATE tankdb.tk_project SET project_name = '行业经济运行分析', project_code = '', project_text = '', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2012-02-01', project_end = null, project_to_dept = '', project_to_user = 4, project_status = 8, project_remark = '', project_lastupdate = '2015-05-20 23:17:00', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 14;
UPDATE tankdb.tk_project SET project_name = '宁德军民融合综合交通规划（交通战备）', project_code = '', project_text = '', project_type = 23, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-08-18', project_end = '2014-08-19', project_to_dept = '', project_to_user = 3, project_status = 2, project_remark = '', project_lastupdate = '2015-05-20 23:19:12', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 15;
UPDATE tankdb.tk_project SET project_name = '赣榆项目专题一修改', project_code = '', project_text = '', project_type = 23, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-08-15', project_end = '2014-09-12', project_to_dept = '', project_to_user = 3, project_status = 24, project_remark = '', project_lastupdate = '2015-05-20 23:18:34', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 16;
UPDATE tankdb.tk_project SET project_name = '交通运输能耗统计体系研究', project_code = '', project_text = '', project_type = 23, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-08-01', project_end = '2015-03-31', project_to_dept = '', project_to_user = 11, project_status = 24, project_remark = '', project_lastupdate = '2015-05-20 23:19:11', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 17;
UPDATE tankdb.tk_project SET project_name = '物流大通道', project_code = '21', project_text = '', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-06-18', project_end = '2015-12-31', project_to_dept = '', project_to_user = 10, project_status = 24, project_remark = '', project_lastupdate = '2015-05-20 23:16:56', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '1', project_manager = '2', project_chief_engineer = '2', project_Director = '2', project_Division_engineer = '1', project_member = '1' WHERE id = 18;
UPDATE tankdb.tk_project SET project_name = '米兰物流园区项目咨询', project_code = '', project_text = '<p>
	现阶段为总体规划，准备2015年可研
</p>', project_type = 23, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-07-01', project_end = '2014-10-31', project_to_dept = '', project_to_user = 3, project_status = 2, project_remark = '', project_lastupdate = '2015-05-20 23:18:35', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 19;
UPDATE tankdb.tk_project SET project_name = '翁部长带队综合交通运输规划与发展机制调研', project_code = '', project_text = '<p>
	主管所长：王伟
</p>
<p>
	课题组成员：赵凛、何明
</p>', project_type = 24, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-08-10', project_end = '2014-10-10', project_to_dept = '', project_to_user = 2, project_status = 4, project_remark = '', project_lastupdate = '2015-05-20 23:19:00', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 20;
UPDATE tankdb.tk_project SET project_name = '2014年人大政协提案回复', project_code = '', project_text = '每人回复8-10份提案，并参与提案把关讨论', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-08-22', project_end = '2014-08-26', project_to_dept = '', project_to_user = 2, project_status = 24, project_remark = '', project_lastupdate = '2015-05-20 23:19:30', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 21;
UPDATE tankdb.tk_project SET project_name = '综合交通运输十三五规划思路', project_code = '', project_text = '<p>
	王所是项目负责人
</p>
<p>
	何力武主要负责形势、要求和发展阶段判断部分
</p>
<p>
	孙鹏负责铁路部分及网络方案，修改阶段负责发展基础部分修改和会议组织
</p>', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-07-09', project_end = '2014-10-31', project_to_dept = '', project_to_user = 6, project_status = 6, project_remark = '', project_lastupdate = '2015-05-20 23:17:01', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 22;
UPDATE tankdb.tk_project SET project_name = '135经济社会发展对交通运输需求的影响', project_code = '', project_text = '', project_type = 23, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-07-01', project_end = '2014-10-09', project_to_dept = '', project_to_user = 4, project_status = 5, project_remark = '', project_lastupdate = '2015-05-20 23:19:10', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 23;
UPDATE tankdb.tk_project SET project_name = '重庆市综合运输枢纽体系', project_code = '', project_text = '', project_type = 23, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-08-19', project_end = '2014-10-31', project_to_dept = '', project_to_user = 1, project_status = 24, project_remark = '', project_lastupdate = '2015-05-20 23:18:36', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 26;
UPDATE tankdb.tk_project SET project_name = '宁波市“十三五”综合交通发展思路与对策研究', project_code = '', project_text = '', project_type = 23, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-06-01', project_end = '2014-12-31', project_to_dept = '', project_to_user = 11, project_status = 24, project_remark = '', project_lastupdate = '2015-05-20 23:19:09', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 27;
UPDATE tankdb.tk_project SET project_name = '德清临杭物流园区II区公共服务中心项目工可和资金申请报告', project_code = '', project_text = '', project_type = 23, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-03-12', project_end = '2014-12-31', project_to_dept = '', project_to_user = 11, project_status = 7, project_remark = '', project_lastupdate = '2015-05-20 23:18:38', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 28;
UPDATE tankdb.tk_project SET project_name = '武汉市综合交通运输体系发展规划', project_code = '', project_text = '', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2012-12-20', project_end = '2014-11-30', project_to_dept = '', project_to_user = 11, project_status = 7, project_remark = '', project_lastupdate = '2015-05-20 23:19:18', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 29;
UPDATE tankdb.tk_project SET project_name = '长江经济带湖北省综合交通运输体系规划', project_code = '', project_text = '', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-07-16', project_end = '2015-05-30', project_to_dept = '', project_to_user = 10, project_status = 5, project_remark = '', project_lastupdate = '2015-05-20 23:17:03', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 30;
UPDATE tankdb.tk_project SET project_name = '所团支部活动及相关工作', project_code = '', project_text = '', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-03-05', project_end = '2016-03-06', project_to_dept = '', project_to_user = 4, project_status = 23, project_remark = '', project_lastupdate = '2015-05-20 23:19:29', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 31;
UPDATE tankdb.tk_project SET project_name = '重庆综合交通运输“十三五”发展规划研究', project_code = '', project_text = '', project_type = 23, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-08-07', project_end = null, project_to_dept = '', project_to_user = 6, project_status = 4, project_remark = '', project_lastupdate = '2015-05-20 23:19:07', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 32;
UPDATE tankdb.tk_project SET project_name = '“十三五”综合运输战略重点及对策研究 ', project_code = '', project_text = '', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-03-01', project_end = '2014-12-01', project_to_dept = '', project_to_user = 6, project_status = 5, project_remark = '', project_lastupdate = '2015-05-20 23:17:05', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 33;
UPDATE tankdb.tk_project SET project_name = '关于万州落实“长江经济带”国家战略的交通发展对策研究', project_code = '', project_text = '', project_type = 23, project_from = '', project_from_user = '', project_from_contact = '', project_start = null, project_end = null, project_to_dept = '', project_to_user = 7, project_status = 2, project_remark = '', project_lastupdate = '2015-05-20 23:18:39', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 34;
UPDATE tankdb.tk_project SET project_name = '关中-天水综合交通规划', project_code = '', project_text = '<p>
	项目负责人张所。
</p>
<p>
	何力武负责经济社会现状、经验借鉴和运输需求三个章节
</p>', project_type = 23, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2012-09-01', project_end = null, project_to_dept = '', project_to_user = 1, project_status = 24, project_remark = '', project_lastupdate = '2015-05-20 23:19:05', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 35;
UPDATE tankdb.tk_project SET project_name = '综合运输经济室头脑风暴会', project_code = '', project_text = '<p>
	综合运输经济室头脑风暴会，主要就改进和提升工作效能查摆工作管理中遇到的问题，王伟副所长参会，会议从3点历时到6点。
</p>', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-09-02', project_end = '2014-09-02', project_to_dept = '', project_to_user = 10, project_status = 23, project_remark = '', project_lastupdate = '2015-05-20 23:19:20', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 36;
UPDATE tankdb.tk_project SET project_name = '《机关党支部工作手册》课题研究', project_code = '', project_text = '受中央机关工委的委托开展此课题，院里由刘韬书记牵头，党办/院办、发条处、综合所和信息所参加。项目负责人为李星野和周国强，金所和唐鹏程代表综合所参加该项目。', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-07-15', project_end = null, project_to_dept = '', project_to_user = 7, project_status = 5, project_remark = '', project_lastupdate = '2015-05-20 23:17:06', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 37;
UPDATE tankdb.tk_project SET project_name = '所项目管理系统研发', project_code = '', project_text = '基于wss系统，参照院所质量管理办法，开发所的项目管理系统，以提高工作效率。', project_type = 24, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-08-01', project_end = '2014-12-31', project_to_dept = '', project_to_user = 2, project_status = 8, project_remark = '', project_lastupdate = '2015-05-20 23:18:52', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 38;
UPDATE tankdb.tk_project SET project_name = '交通运输推进物流园区建设政策和实施方案', project_code = '', project_text = '部2013年指令性任务。旨在总结十二五推进货运枢纽（物流园区）建设存在的问题，提出今后行业推进此项工作的政策建议和实施重点。', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2013-01-01', project_end = '2014-12-31', project_to_dept = '', project_to_user = 10, project_status = 7, project_remark = '', project_lastupdate = '2015-05-20 23:19:27', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 39;
UPDATE tankdb.tk_project SET project_name = '江苏省综合交通物流枢纽规划', project_code = '', project_text = '解读综合交通物流枢纽内涵、提出分级分类指标要求；分析全省构建综合交通物流枢纽体系的需求、定位、架构、层次，并拟定重点项目和近期实施计划。', project_type = 23, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2013-09-01', project_end = '2014-12-31', project_to_dept = '', project_to_user = 10, project_status = 5, project_remark = '', project_lastupdate = '2015-05-20 23:18:40', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 40;
UPDATE tankdb.tk_project SET project_name = '临时性任务-政务分析报告', project_code = '', project_text = '<p>
	来自部办公厅督查室
</p>
<p>
	前一轮工作已完成：工作思路的拟定；并对督查管理办法提意见
</p>', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-08-13', project_end = '2014-09-30', project_to_dept = '', project_to_user = 4, project_status = 8, project_remark = '', project_lastupdate = '2015-05-20 23:17:10', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 42;
UPDATE tankdb.tk_project SET project_name = '连云港港赣榆港区物流发展规划', project_code = '', project_text = '', project_type = 23, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2013-10-15', project_end = '2014-12-31', project_to_dept = '', project_to_user = 14, project_status = 24, project_remark = '', project_lastupdate = '2015-05-20 23:19:03', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 43;
UPDATE tankdb.tk_project SET project_name = '重庆忠县物流园区概念规划', project_code = '', project_text = '<p style="text-indent:28pt;">
	<p style="text-indent:28pt;" align="left">
		<span style="font-family:宋体;line-height:150%;">研究制定忠县县域范围内物流系统的顶层设计方案，并</span><span style="font-family:宋体;">对忠县重点物流园区进行概念规划，</span><span style="font-family:宋体;">寻求忠县物流发展的优势及特色。</span> 
	</p>
	<p>
		<br />
	</p>', project_type = 23, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-02-01', project_end = '2014-12-31', project_to_dept = '', project_to_user = 31, project_status = 24, project_remark = '', project_lastupdate = '2015-05-20 23:18:41', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 44;
UPDATE tankdb.tk_project SET project_name = '东莞市珠江口东岸地区临港现代产业集聚区规划', project_code = '', project_text = '<p>
	分一个主报告（李伟负责），三个专题，分别是产业专题（北大负责）、长安新区（我所统筹北大和水运所，何力武负责）、交通专题（陆晓华、孙鹏）
</p>
<p>
	跨所合作，外部联合北京大学区域研究中心
</p>
<p>
	所内副总:　陈璟
</p>
<p>
	院总工：朱鲁存
</p>
<p>
	所主管所长：王伟
</p>
<p>
	<br />
</p>', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2013-06-13', project_end = '2014-07-18', project_to_dept = '', project_to_user = 10, project_status = 8, project_remark = '', project_lastupdate = '2015-05-20 23:17:44', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 45;
UPDATE tankdb.tk_project SET project_name = '西部港口物流枢纽规划与布局技术研究及示范应用', project_code = '', project_text = '', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2012-06-01', project_end = '2014-10-31', project_to_dept = '', project_to_user = 10, project_status = 8, project_remark = '', project_lastupdate = '2015-05-20 23:17:48', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 47;
UPDATE tankdb.tk_project SET project_name = '中国物流战略合作', project_code = '', project_text = '', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-08-18', project_end = '2014-10-30', project_to_dept = '', project_to_user = 10, project_status = 23, project_remark = '', project_lastupdate = '2015-05-20 23:17:46', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 48;
UPDATE tankdb.tk_project SET project_name = '义乌国际陆港新区发展战略研究', project_code = '', project_text = '根据建设联合国建设国际陆港有关要求，结合义乌实际和新一轮城市总规调整，提出国际陆港新区物流核心战略定位、区功能优化调整建议等', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-08-24', project_end = '2015-03-31', project_to_dept = '', project_to_user = 2, project_status = 2, project_remark = '', project_lastupdate = '2015-05-20 23:19:22', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 49;
UPDATE tankdb.tk_project SET project_name = '铁路十三五规划思路与对策', project_code = '', project_text = '', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-06-01', project_end = '2014-12-31', project_to_dept = '', project_to_user = 2, project_status = 24, project_remark = '', project_lastupdate = '2015-05-20 23:17:49', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 50;
UPDATE tankdb.tk_project SET project_name = '临时性项目—部党组2014年第7次党组中心组学习材料准备', project_code = '', project_text = '李院长准备部党组2014年第7次党组中心组学习发言的ppt，唐鹏程、陈宇毅参加', project_type = 24, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-09-24', project_end = '2014-09-26', project_to_dept = '', project_to_user = 7, project_status = 9, project_remark = '', project_lastupdate = '2015-05-20 23:18:57', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 52;
UPDATE tankdb.tk_project SET project_name = '长江经济带综合运输体系规划', project_code = '', project_text = '', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-09-26', project_end = '2015-12-31', project_to_dept = '', project_to_user = 6, project_status = 23, project_remark = '', project_lastupdate = '2015-05-20 23:19:25', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 53;
UPDATE tankdb.tk_project SET project_name = '华威公路港物流园区', project_code = '', project_text = '项目请款', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-10-08', project_end = '2014-10-20', project_to_dept = '', project_to_user = 1, project_status = 8, project_remark = '', project_lastupdate = '2015-05-20 23:17:50', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 54;
UPDATE tankdb.tk_project SET project_name = '综合所2015年日常工作例行会议', project_code = '', project_text = '<p>
	综合所各月例行所务会及、务虚会和全所参加的工作会议
</p>', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2015-01-01', project_end = '2015-12-31', project_to_dept = '', project_to_user = 42, project_status = 23, project_remark = '', project_lastupdate = '2015-05-20 23:18:19', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 55;
UPDATE tankdb.tk_project SET project_name = '沈本新城客运枢纽站工程可行性研究', project_code = '', project_text = '', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-05-01', project_end = '2014-10-31', project_to_dept = '', project_to_user = 13, project_status = 9, project_remark = '', project_lastupdate = '2015-05-20 23:17:51', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 56;
UPDATE tankdb.tk_project SET project_name = '沈本新城客运枢纽站资金申请报告', project_code = '', project_text = '', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-10-01', project_end = '2015-01-15', project_to_dept = '', project_to_user = 13, project_status = 7, project_remark = '', project_lastupdate = '2015-05-20 23:18:07', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 57;
UPDATE tankdb.tk_project SET project_name = 'GEF城市客运枢纽规划与功能优化技术指南', project_code = '', project_text = '', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2015-01-08', project_end = '2015-08-31', project_to_dept = '', project_to_user = 19, project_status = 5, project_remark = '', project_lastupdate = '2015-05-20 23:17:52', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 58;
UPDATE tankdb.tk_project SET project_name = '“十三五”期江西省综合交通运输体系发展研究', project_code = '', project_text = '<p>
	本课题是江西省交通运输厅组织开展的12个“十三五”规划前期重大研究课题之一，也是首个组织开展大纲评审的课题。课题在分析新形势下江西综合交通运输体系发展现状与趋势基础上，研究提出“十三五”期江西省综合交通运输体系发展的指导思想、发展目标、重点任务、保障措施等内容，<span style="line-height:1.5;">课题研究成果将为指导江西省交通运输“十三五”规划编制提供重要参考</span><span style="line-height:1.5;"></span><span style="line-height:1.5;">和指导</span><span style="line-height:1.5;">。</span> 
</p>', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-10-15', project_end = '2015-05-31', project_to_dept = '', project_to_user = 30, project_status = 6, project_remark = '', project_lastupdate = '2015-05-20 23:18:22', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 59;
UPDATE tankdb.tk_project SET project_name = '综合运输规划决策支持系统（基建）', project_code = '', project_text = '', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2015-01-09', project_end = '2015-01-16', project_to_dept = '', project_to_user = 36, project_status = 8, project_remark = '', project_lastupdate = '2015-05-20 23:17:53', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 60;
UPDATE tankdb.tk_project SET project_name = '河北省交通运输现代化研究', project_code = '', project_text = '<br />', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2015-01-06', project_end = '2015-06-30', project_to_dept = '', project_to_user = 15, project_status = 5, project_remark = '', project_lastupdate = '2015-05-20 23:18:08', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 61;
UPDATE tankdb.tk_project SET project_name = '平顶山市综合交通运输体系规划研究', project_code = '', project_text = '', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2015-01-28', project_end = null, project_to_dept = '', project_to_user = 35, project_status = 7, project_remark = '', project_lastupdate = '2015-05-20 23:17:54', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 62;
UPDATE tankdb.tk_project SET project_name = '重庆市十三五综合运输枢纽发展对策研究', project_code = '', project_text = '', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2015-01-28', project_end = null, project_to_dept = '', project_to_user = 35, project_status = 5, project_remark = '', project_lastupdate = '2015-05-20 23:18:21', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 63;
UPDATE tankdb.tk_project SET project_name = '重庆市十三五综合运输枢纽建设规划', project_code = '', project_text = '', project_type = 24, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2015-01-28', project_end = null, project_to_dept = '', project_to_user = 35, project_status = 5, project_remark = '', project_lastupdate = '2015-05-20 23:18:54', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 65;
UPDATE tankdb.tk_project SET project_name = '十堰市十三五公路水路交通运输发展规划', project_code = '', project_text = '', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2015-01-28', project_end = null, project_to_dept = '', project_to_user = 35, project_status = 5, project_remark = '', project_lastupdate = '2015-05-20 23:18:10', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 66;
UPDATE tankdb.tk_project SET project_name = '关中—天水经济区主要城市公路过境方案研究', project_code = '', project_text = '', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2015-01-28', project_end = null, project_to_dept = '', project_to_user = 35, project_status = 5, project_remark = '', project_lastupdate = '2015-05-20 23:17:56', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 67;
UPDATE tankdb.tk_project SET project_name = '烟台市综合交通运输体系发展规划', project_code = '', project_text = '（1）编制《烟台市综合交通运输体系发展规划》研究报告；<br />
（2）编制《烟台市综合交通运输体系发展规划纲要》。', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2015-01-30', project_end = '2015-10-31', project_to_dept = '', project_to_user = 30, project_status = 4, project_remark = '', project_lastupdate = '2015-05-20 23:18:27', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 68;
UPDATE tankdb.tk_project SET project_name = '烟台市交通运输”十三五“发展规划', project_code = '', project_text = '编制《烟台市交通运输“十三五”发展规划》。', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2015-01-31', project_end = '2015-12-31', project_to_dept = '', project_to_user = 30, project_status = 4, project_remark = '', project_lastupdate = '2015-05-20 23:17:57', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 70;
UPDATE tankdb.tk_project SET project_name = '泸州综合运输服务示范城市建设实施方案', project_code = '', project_text = '&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;根据交通运输部文件《交通运输部关于开展综合运输服务示范城市建设的通知》，编制泸州综合运输服务示范城市建设实施方案，争取将泸州市纳入交通运输部综合运输服务示范城市。', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-12-31', project_end = '2015-04-01', project_to_dept = '', project_to_user = 34, project_status = 24, project_remark = '', project_lastupdate = '2015-05-20 23:18:12', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 71;
UPDATE tankdb.tk_project SET project_name = '昭通市综合交通运输“十三五”发展规划', project_code = '', project_text = '&nbsp; &nbsp;&nbsp;统筹各种运输方式发展，编制《昭通市综合交通运输“十三五”发展规划》。', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2015-01-26', project_end = '2015-06-30', project_to_dept = '', project_to_user = 34, project_status = 2, project_remark = '', project_lastupdate = '2015-05-20 23:17:58', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 72;
UPDATE tankdb.tk_project SET project_name = '广东省交通运输发展评价研究', project_code = '', project_text = '&nbsp; &nbsp;&nbsp;开展广东省交通运输发展评价研究，客观分析广东省交通运输发展现状水平以及与发达国家（地区）的差距，准确把握交通运输体系的薄弱环节和发展中存在的主要问题。', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2013-07-01', project_end = '2015-05-01', project_to_dept = '', project_to_user = 34, project_status = 7, project_remark = '', project_lastupdate = '2015-05-20 23:16:41', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 73;
UPDATE tankdb.tk_project SET project_name = '恩施汽车客运中心站项目资金申请报告', project_code = '', project_text = '&nbsp; &nbsp;&nbsp;根据《交通运输部综合客运枢纽项目计划管理暂行规定》相关要求，编制《恩施综合客运枢纽汽车恩施客运中心站项目资金申请报告》。', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2012-10-08', project_end = '2015-03-31', project_to_dept = '', project_to_user = 34, project_status = 8, project_remark = '', project_lastupdate = '2015-05-20 23:18:25', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 74;
UPDATE tankdb.tk_project SET project_name = '关中—天水经济区民用航空发展规划研究', project_code = '', project_text = '&nbsp; &nbsp; &nbsp;按照《关中—天水经济区综合运输体系发展规划》主报告的要求，编写《关中—天水经济区民用航空发展规划研究》报告。', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2012-05-07', project_end = '2015-12-31', project_to_dept = '', project_to_user = 34, project_status = 24, project_remark = '', project_lastupdate = '2015-05-20 23:17:59', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 75;
UPDATE tankdb.tk_project SET project_name = '经济室技术交流', project_code = '', project_text = '', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2015-01-01', project_end = '2015-02-08', project_to_dept = '', project_to_user = 10, project_status = 23, project_remark = '', project_lastupdate = '2015-05-20 23:18:14', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 76;
UPDATE tankdb.tk_project SET project_name = '决策支持系统建设', project_code = '', project_text = '', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-11-01', project_end = '2015-12-31', project_to_dept = '', project_to_user = 36, project_status = 24, project_remark = '', project_lastupdate = '2015-05-20 23:18:00', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 77;
UPDATE tankdb.tk_project SET project_name = '我国与周边国家交通基础设施互联互通发展思路与对策研究', project_code = '', project_text = '', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-04-13', project_end = '2015-12-30', project_to_dept = '', project_to_user = 18, project_status = 5, project_remark = '', project_lastupdate = '2015-05-20 23:18:18', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 78;
UPDATE tankdb.tk_project SET project_name = '新疆建设一带一路交通枢纽中心战略研究', project_code = '', project_text = '', project_type = 23, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2014-03-13', project_end = '2015-06-20', project_to_dept = '', project_to_user = 18, project_status = 7, project_remark = '', project_lastupdate = '2015-05-20 23:19:02', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 79;
UPDATE tankdb.tk_project SET project_name = '集装箱铁水联运通道与货运枢纽布局规划', project_code = '', project_text = '', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2013-03-13', project_end = '2015-03-20', project_to_dept = '', project_to_user = 18, project_status = 6, project_remark = '', project_lastupdate = '2015-05-20 23:18:02', project_importance = '', project_source = '', project_month_eval = 0, project_dean = '', project_manager = '', project_chief_engineer = '', project_Director = '', project_Division_engineer = '', project_member = '' WHERE id = 80;
UPDATE tankdb.tk_project SET project_name = '交通运输建设一带一路工作思路及方案研究', project_code = '1', project_text = '测试', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2015-02-13', project_end = '2016-03-20', project_to_dept = '', project_to_user = 18, project_status = 4, project_remark = '', project_lastupdate = '2015-05-20 23:18:06', project_importance = '重要', project_source = '交通部', project_month_eval = 2, project_dean = '1', project_manager = '1', project_chief_engineer = '1', project_Director = '1', project_Division_engineer = '1', project_member = '1' WHERE id = 81;
UPDATE tankdb.tk_project SET project_name = '交通运输建设一带一路工作思路及方案研究11', project_code = '', project_text = '', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2015-05-19', project_end = '2015-05-26', project_to_dept = '', project_to_user = 8, project_status = 2, project_remark = '', project_lastupdate = '2015-05-20 15:38:31', project_importance = '一般', project_source = '交通部', project_month_eval = 1, project_dean = '43', project_manager = '8', project_chief_engineer = '24', project_Director = '20', project_Division_engineer = '30', project_member = '19,10,39,18' WHERE id = 82;
UPDATE tankdb.tk_project SET project_name = '只写项目名称111111', project_code = '', project_text = '', project_type = 22, project_from = '', project_from_user = '', project_from_contact = '', project_start = '2015-05-20', project_end = '2015-05-27', project_to_dept = '', project_to_user = 1, project_status = 2, project_remark = '', project_lastupdate = '2015-05-20 15:58:04', project_importance = '一般', project_source = '交通部', project_month_eval = 1, project_dean = '1', project_manager = '1', project_chief_engineer = '1', project_Director = '1', project_Division_engineer = '1', project_member = '1' WHERE id = 83;
